name: Run Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "*/59 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: تحميل الكود
        uses: actions/checkout@v3

      - name: تثبيت Node
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: تثبيت المكتبات
        run: yarn install

      - name: تشغيل البوت
        run: node index.js
